### ISSUE TITLE
Things we should do

### ISSUE THREAD

**Issue by givenone** [thunderlink/ThunderFish#41]
1. Kakao login
- backend : 성찬
- frontend : 동우, 준원

2. Join/ Accept/ Deny
- backend : cooperate with front (성찬)
- front : 동우, 준원

3. Pricing system
(1) backend :  (종호)
-  should modify model's field
-  think about algorithm : when accept (pricing should be little bit different for each person, and sum of all price should be equal to the total cost) (종호 should think about it. Do it with your own branch)
(2) front :
- No need to do something special. Back will deal with it.

4. chatting room
- only front : (준원)
I will find some ways to make kakao open chatting room using apis. I think we can redirect page to the chatting room making page. 
It would be much better avoiding something complex (socket, ... )

5. Improve searching system (NOT ESSENTIAL)
- back only : (Lets talk about it later)
Maybe, we can improve our searching system (search by meeting name, ....... and cover other things also)
Map based search, Time based search(마감 임박..)

6. Map Api
- back :
get coordinate or region from front, and can search nearest meetings. (종호, 성찬)
- front :
Finish kakao map api, and Let's think about region-generation ( "동" or "구" based?)
after back finish their job, we should make map-based search component. (동우, 준원)

7. Grading System.
- back :
should change profile or user model, and should make api
- front :
should make interface after closing meeting.

8. UX improvement (last thing to do)
- making recommendation system
- At the Main page, little bit easier way to see the meetings

Things we should do UNTIL NEXT MONDAY (6.03rd)

(1) KAKAO LOGIN
(2) JOIN/ACCEPT
(4) Chatting
(6) Map Api

Thing we should do during next iteration

(3) Pricing system
(4) Searching Improvement
(7) Grading system (평가)
(8) UX improvement

**Comment by KRKimDongWoo** [comment]
1. Good

2. Good

3, 5. (3) might be a good feature of our web, but I don't think it is not important for our main purpose. We do not need pricing system for every meetings.(i.e. Sports, Study...) It will be better to focus on 5 first, since most important feature for our web is Searching. Also, we have to chose our format of sending options (locale, time, ...) to backend. Therefore, (5) will require more important and various works for us, so it should be done at first

4. It might be enough for make open chatting link. Therefore, Let's just leave it as open chatting link, and focus on other works. Kakao api does not support create open chatting itself.

6. As I mentioned before, **region can be revealed from coordinate**. Therefore,  the only thing we need is coordinate and place name. I will deal it with myself.

7. Good, only need trivial modification on backend and frontend.

8. Already asked for help to 성찬, 종호, by showing recent meetings created.

+ Currently modifying UI of our website. I will push it until today. It will be look similar to [react-reduction template](https://github.com/reduction-admin/react-reduction).

**Comment by KRKimDongWoo** [comment]
1, 2, 5, 6 done,
3, 4, 7, 8 will not be implemented on this project.
